<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Frank Frisbie">
<meta name="dcterms.date" content="2026-07-08">

<title>Do Presidents Govern by Decree When They Lose Congress?</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-67270d1595a62d14f123c043d4fb2f18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-claim-being-tested" id="toc-the-claim-being-tested" class="nav-link active" data-scroll-target="#the-claim-being-tested">The claim being tested</a></li>
  <li><a href="#what-counts-as-divided-and-where-the-numbers-come-from" id="toc-what-counts-as-divided-and-where-the-numbers-come-from" class="nav-link" data-scroll-target="#what-counts-as-divided-and-where-the-numbers-come-from">What counts as “divided,” and where the numbers come from</a></li>
  <li><a href="#the-result" id="toc-the-result" class="nav-link" data-scroll-target="#the-result">The result</a>
  <ul class="collapse">
  <li><a href="#robustness" id="toc-robustness" class="nav-link" data-scroll-target="#robustness">Robustness</a></li>
  </ul></li>
  <li><a href="#how-fragile-is-this-null" id="toc-how-fragile-is-this-null" class="nav-link" data-scroll-target="#how-fragile-is-this-null">How fragile is this null?</a></li>
  <li><a href="#what-this-does-and-doesnt-show" id="toc-what-this-does-and-doesnt-show" class="nav-link" data-scroll-target="#what-this-does-and-doesnt-show">What this does and doesn’t show</a></li>
  <li><a href="#reproduce-this" id="toc-reproduce-this" class="nav-link" data-scroll-target="#reproduce-this">Reproduce this</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Do Presidents Govern by Decree When They Lose Congress?</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">A pre-registered test of executive orders under divided government, 1953–2025</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Frank Frisbie </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 8, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr); <span class="fu">library</span>(readr); <span class="fu">library</span>(broom); <span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/00_shared.R"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>eos     <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/executive_orders_raw.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>divided <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/divided_government.csv"</span>,   <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>panel   <span class="ot">&lt;-</span> <span class="fu">build_panel</span>(eos, divided)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>models  <span class="ot">&lt;-</span> <span class="fu">fit_models</span>(panel)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>nb      <span class="ot">&lt;-</span> models[[<span class="st">"Negative binomial (primary)"</span>]]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Profile-likelihood CIs where computable; Wald-CI fallback only when profiling</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># fails. The president fixed-effects spec has complete separation on this small</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># sample, so its profile CI cannot be computed - this keeps that spec in the</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># robustness table (as pre-registered) instead of aborting the render. The other</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># three specs are unaffected and keep their exact profile intervals.</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>tidy_ci <span class="ot">&lt;-</span> <span class="cf">function</span>(m) {</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tryCatch</span>(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>(m, <span class="at">conf.int =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>      z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">tidy</span>(m) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">conf.low  =</span> estimate <span class="sc">-</span> z <span class="sc">*</span> std.error,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>                        <span class="at">conf.high =</span> estimate <span class="sc">+</span> z <span class="sc">*</span> std.error)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="the-claim-being-tested" class="level2">
<h2 class="anchored" data-anchor-id="the-claim-being-tested">The claim being tested</h2>
<p>A familiar story about American politics: when a president faces a Congress controlled by the other party, they stop legislating and start <em>decreeing</em>, reaching for the executive order to act without lawmakers. It’s intuitive, it’s repeated constantly, and it has serious scholarship behind it (Howell, <em>Power Without Persuasion</em>; Mayer, <em>With the Stroke of a Pen</em>).</p>
<p>This is a small, deliberately narrow test of one measurable piece of that story: <strong>does the raw volume of executive orders rise under divided government?</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>This analysis was pre-registered
</div>
</div>
<div class="callout-body-container callout-body">
<p>The hypothesis and the full model specification were frozen <strong>before any data was pulled or seen</strong>. See <a href="PRE_REGISTRATION.md"><code>PRE_REGISTRATION.md</code></a>. That means the result below was not reverse-engineered to be interesting. A clean null is reported as honestly as a clean positive.</p>
</div>
</div>
</section>
<section id="what-counts-as-divided-and-where-the-numbers-come-from" class="level2">
<h2 class="anchored" data-anchor-id="what-counts-as-divided-and-where-the-numbers-come-from">What counts as “divided,” and where the numbers come from</h2>
<p>Every number here traces to a public source:</p>
<ul>
<li><strong>Executive orders</strong>: the complete 1953–2025 record, counted by signing date. The Federal Register’s search API only has full coverage from 1994 on, so the pipeline combines its pre-1994 disposition tables with the 1994+ API, then validates per-president totals against published counts and refuses to run if the data is incomplete.</li>
<li><strong>Party control of each chamber</strong>: hand-verified per Congress (to correctly handle caucusing independents and VP-tiebreak Senates that a naive party count miscodes), and independently cross-checked against <a href="https://voteview.com">voteview.com</a> DW-NOMINATE records.</li>
<li><strong>Presidential party</strong>: a 14-row administrations table.</li>
</ul>
<p>A year is coded <strong>divided</strong> when the president’s party does not control <em>both</em> chambers.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>panel <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(control) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at"># years</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">n</span>(), <span class="st">`</span><span class="at">avg EOs/yr</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(eo_count), <span class="dv">1</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">control</th>
<th style="text-align: right;"># years</th>
<th style="text-align: right;">avg EOs/yr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">opposition_congress</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">48.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">split_congress</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">43.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">unified</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">66.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">make_timeline_plot</span>(panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/timeline-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-result" class="level2">
<h2 class="anchored" data-anchor-id="the-result">The result</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">tidy</span>(nb, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"divided_government"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>irr <span class="ot">&lt;-</span> <span class="fu">exp</span>(res<span class="sc">$</span>estimate); lo <span class="ot">&lt;-</span> <span class="fu">exp</span>(res<span class="sc">$</span>conf.low); hi <span class="ot">&lt;-</span> <span class="fu">exp</span>(res<span class="sc">$</span>conf.high)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>sig <span class="ot">&lt;-</span> (res<span class="sc">$</span>conf.low <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|</span> (res<span class="sc">$</span>conf.high <span class="sc">&lt;</span> <span class="dv">0</span>)   <span class="co"># CI excludes zero?</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>dir <span class="ot">&lt;-</span> <span class="cf">if</span> (res<span class="sc">$</span>estimate <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="st">"more"</span> <span class="cf">else</span> <span class="st">"fewer"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>verdict <span class="ot">&lt;-</span> <span class="cf">if</span> (sig <span class="sc">&amp;&amp;</span> res<span class="sc">$</span>estimate <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"supports H1: divided government is associated with measurably more executive orders."</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span> (sig <span class="sc">&amp;&amp;</span> res<span class="sc">$</span>estimate <span class="sc">&lt;</span> <span class="dv">0</span>) {</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"runs *against* H1: divided government is associated with measurably fewer executive orders."</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"does **not** support H1: the divided-government association is not statistically distinguishable from zero in this sample."</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>The cleanest specification shows no reliable effect.</strong> Comparing each president against himself with president fixed effects, moving between unified and divided control is associated with essentially no change in how many executive orders a president issues (within-president estimate −0.07, 95% CI includes zero). The popular claim that presidents govern by decree when they lose Congress is not supported here. That null is not bulletproof, though: it turns on how a handful of transition years are coded, which the section <a href="#how-fragile-is-this-null">How fragile is this null?</a> works through in full.</p>
<p>The pooled estimate points the other way, and does not survive that check. In the pre-registered primary model (pooled negative binomial), a divided-government year carries about <strong>0.8×</strong> the executive-order rate of a unified-government year (95% CI 0.68–0.94), that is, fewer orders. Taken by itself, the data runs <em>against</em> H1: divided government is associated with measurably fewer executive orders. But it is the pooled estimate only: it does not survive president fixed effects, so it is best read as a between-president composition pattern (some presidents simply governed in high-EO eras under unified control), not as evidence that divided government itself changes how often a president reaches for the pen. The conclusion the analysis lands on is “no reliable effect,” not “fewer.”</p>
<p>Full coefficient table for the primary specification:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(nb, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), \(x) <span class="fu">round</span>(x, <span class="dv">3</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4.000</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">57.266</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">3.862</td>
<td style="text-align: right;">4.142</td>
</tr>
<tr class="even">
<td style="text-align: left;">divided_government</td>
<td style="text-align: right;">-0.225</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">-2.779</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">-0.387</td>
<td style="text-align: right;">-0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left;">first_year_of_term</td>
<td style="text-align: right;">0.487</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">5.008</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.293</td>
<td style="text-align: right;">0.685</td>
</tr>
<tr class="even">
<td style="text-align: left;">year_centered</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">-3.398</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">-0.003</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="robustness" class="level3">
<h3 class="anchored" data-anchor-id="robustness">Robustness</h3>
<p>The pre-registration committed to reporting four specifications, not just the favorable one. The estimated divided-government effect across all of them:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">map_dfr</span>(<span class="fu">names</span>(models), \(nm) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy_ci</span>(models[[nm]]) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"divided_government"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">transmute</span>(<span class="at">specification =</span> nm, <span class="at">estimate =</span> <span class="fu">round</span>(estimate, <span class="dv">3</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">conf.low =</span> <span class="fu">round</span>(conf.low, <span class="dv">3</span>), <span class="at">conf.high =</span> <span class="fu">round</span>(conf.high, <span class="dv">3</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">p.value =</span> <span class="fu">round</span>(p.value, <span class="dv">3</span>))</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">specification</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Negative binomial (primary)</td>
<td style="text-align: right;">-0.225</td>
<td style="text-align: right;">-0.387</td>
<td style="text-align: right;">-0.064</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left;">Poisson</td>
<td style="text-align: right;">-0.242</td>
<td style="text-align: right;">-0.307</td>
<td style="text-align: right;">-0.176</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OLS</td>
<td style="text-align: right;">-13.335</td>
<td style="text-align: right;">-25.364</td>
<td style="text-align: right;">-1.305</td>
<td style="text-align: right;">0.030</td>
</tr>
<tr class="even">
<td style="text-align: left;">NB + president fixed effects</td>
<td style="text-align: right;">-0.066</td>
<td style="text-align: right;">-0.210</td>
<td style="text-align: right;">0.077</td>
<td style="text-align: right;">0.364</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Reading across specifications.</strong> In the pooled models (negative binomial, Poisson, OLS), divided-government years carry a lower executive-order rate than unified years, about 0.80× in the primary model, statistically distinguishable from zero. That already cuts against H1, which predicted <em>more</em> unilateral action under divided government. But the effect does not survive president fixed effects: within a given presidency, moving between unified and divided control is associated with essentially no change (−0.07, 95% CI includes zero). As the pre-registration flagged in advance, an effect that appears pooled but vanishes within-president is best read as a between-president composition pattern (some presidents simply governed in high-EO eras under unified control), not as evidence that divided government itself changes how often a president reaches for the pen. The raw averages agree: opposition-Congress years (48.2/yr) edge out split-Congress years (43.6/yr), so there is no clean “more division, fewer orders” gradient.</p>
<p><strong>Bottom line.</strong> The popular claim that presidents govern by decree when they lose Congress is not supported here: the pooled association runs the other way (fewer, not more), and it does not survive president fixed effects. But this null is not robust to coding choices. An independent coding disagrees with ours on three of seventy-three years, and adopting it in full would flip the fixed-effects estimate to a significant negative effect. The honest read, developed in the next section, is that <strong>neither the effect nor its absence is robust to how a handful of transition years are coded.</strong></p>
</section>
</section>
<section id="how-fragile-is-this-null" class="level2">
<h2 class="anchored" data-anchor-id="how-fragile-is-this-null">How fragile is this null?</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(MASS))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cap <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/cap_divided_government.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>fe_irrp <span class="ot">&lt;-</span> <span class="cf">function</span>(p){ m <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="fu">update</span>(EO_FORMULA, . <span class="sc">~</span> . <span class="sc">+</span> <span class="fu">factor</span>(president)), <span class="at">data =</span> p)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m))[<span class="st">"divided_government"</span>, ]; <span class="fu">c</span>(<span class="at">irr =</span> <span class="fu">exp</span>(<span class="fu">unname</span>(s[<span class="dv">1</span>])), <span class="at">p =</span> <span class="fu">unname</span>(s[<span class="dv">4</span>])) }</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>setyr <span class="ot">&lt;-</span> <span class="cf">function</span>(p, yrs, v){ p<span class="sc">$</span>divided_government[p<span class="sc">$</span>year <span class="sc">%in%</span> yrs] <span class="ot">&lt;-</span> v; p }</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>panel_cap <span class="ot">&lt;-</span> panel; panel_cap<span class="sc">$</span>divided_government <span class="ot">&lt;-</span> cap<span class="sc">$</span>cap_divided[<span class="fu">match</span>(panel<span class="sc">$</span>year, cap<span class="sc">$</span>year)]</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>fe_ours <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(panel)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>fe_j    <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(<span class="fu">setyr</span>(panel, <span class="fu">c</span>(<span class="dv">2001</span>,<span class="dv">2002</span>), <span class="dv">0</span>))   <span class="co"># CAP's Jeffords convention only</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>fe_2018 <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(<span class="fu">setyr</span>(panel, <span class="dv">2018</span>, <span class="dv">1</span>))           <span class="co"># CAP's 2018 only</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>fe_cap  <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(panel_cap)                        <span class="co"># full CAP coding</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>irrp <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sprintf</span>(<span class="st">"IRR %.3f, p = %.3f"</span>, x[<span class="st">"irr"</span>], x[<span class="st">"p"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>To see how sturdy the “no reliable effect” conclusion is, I checked it against an <strong>independent coding</strong> of the same orders: the Comparative Agendas Project executive-orders dataset (1945-2025), which codes each order with its own divided-government flag. Collapsed to the year level, <strong>it agrees with our coding on 70 of 73 years.</strong> But the three disagreements are enough to move the headline.</p>
<p>Under our coding, the president-fixed-effects estimate shows <strong>no reliable effect</strong> (IRR 0.936, p = 0.364). Under CAP’s full coding, the same model would show a <strong>statistically significant negative effect</strong> (IRR 0.840, p = 0.036), which would overturn the headline from “no reliable effect” to “reliably fewer orders under divided government.”</p>
<p>Because the disagreement is only three years, it is worth seeing exactly how each one moves the fixed-effects estimate:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Coding =</span> <span class="fu">c</span>(<span class="st">"Ours (hand-coded control)"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>             <span class="st">"+ CAP's 2001-2002 (Jeffords) only"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"+ CAP's 2018 only"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Full CAP coding (all three years)"</span>),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">IRR (divided govt)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">c</span>(fe_ours[<span class="st">"irr"</span>], fe_j[<span class="st">"irr"</span>], fe_2018[<span class="st">"irr"</span>], fe_cap[<span class="st">"irr"</span>]), <span class="dv">3</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">p-value</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">c</span>(fe_ours[<span class="st">"p"</span>], fe_j[<span class="st">"p"</span>], fe_2018[<span class="st">"p"</span>], fe_cap[<span class="st">"p"</span>]), <span class="dv">3</span>),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Reliable effect?</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"no"</span>, <span class="st">"no"</span>, <span class="st">"yes (negative)"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 43%">
<col style="width: 24%">
<col style="width: 10%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Coding</th>
<th style="text-align: right;">IRR (divided govt)</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: left;">Reliable effect?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ours (hand-coded control)</td>
<td style="text-align: right;">0.936</td>
<td style="text-align: right;">0.364</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="even">
<td style="text-align: left;">+ CAP’s 2001-2002 (Jeffords) only</td>
<td style="text-align: right;">0.898</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="odd">
<td style="text-align: left;">+ CAP’s 2018 only</td>
<td style="text-align: right;">0.891</td>
<td style="text-align: right;">0.114</td>
<td style="text-align: left;">no</td>
</tr>
<tr class="even">
<td style="text-align: left;">Full CAP coding (all three years)</td>
<td style="text-align: right;">0.840</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: left;">yes (negative)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Adopting CAP’s 2001-2002 coding alone leaves the null intact (p = 0.200). Adopting CAP’s 2018 coding alone leaves it intact (p = 0.114). Only both together cross into significance (p = 0.036).</p>
<p>Our reasoning, without hedging:</p>
<ul>
<li><strong>2001-2002 is a genuine convention difference.</strong> CAP codes by which party <em>organized</em> the chamber; we hand-code <em>actual</em> control. After Senator Jeffords left the Republican caucus in mid-2001, the Senate was Democratic-controlled, so we code 2001-2002 as divided. This choice was frozen in advance (pre-registration, limitation 3), not chosen to produce a result.</li>
<li><strong>2018 is not a convention difference. It is an apparent error.</strong> 2018 falls in the 115th Congress, which was unified Republican control. CAP files 2018’s orders under the 116th Congress, which did not convene until January 2019. We do not adopt a coding we believe is mistaken in order to obtain significance.</li>
</ul>
<p>So the null <strong>survives every individually defensible recoding, and breaks only under a combination that includes the apparent error.</strong> That is the most defensible reading of the evidence. But the plain fact that a three-year recoding in a seventy-three-year series can flip the result means the honest conclusion is the one stated above: <strong>neither the effect nor its absence is robust to coding choices.</strong> A longer series, or a settled convention for mid-Congress control flips, would be needed to say more.</p>
</section>
<section id="what-this-does-and-doesnt-show" class="level2">
<h2 class="anchored" data-anchor-id="what-this-does-and-doesnt-show">What this does and doesn’t show</h2>
<ul>
<li><strong>Counts ≠ significance.</strong> This measures the <em>volume</em> of unilateral action, not its weight. A single consequential order and a routine administrative one count the same. Raw counts are known to undercount the orders that matter most.</li>
<li><strong>EOs are one channel.</strong> Memoranda and proclamations are other unilateral tools, out of scope here.</li>
<li><strong>Small sample.</strong> ~73 years means wide confidence intervals; that uncertainty is shown, not smoothed over.</li>
<li><strong>Mid-Congress control flips</strong> (e.g., the 2001 Senate) are coded at the Congress level and tested in robustness.</li>
<li><strong>Completeness was the hard part.</strong> An initial pull silently captured only ~1,485 of the ~3,800 orders because of the API’s pre-1994 gap, which by itself faked a result. The analysis proceeds only after a per-president completeness check passes.</li>
</ul>
</section>
<section id="reproduce-this" class="level2">
<h2 class="anchored" data-anchor-id="reproduce-this">Reproduce this</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> R/01_pull_executive_orders.R     <span class="co"># pull EOs from the Federal Register</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> R/02_build_divided_government.R   <span class="co"># derive chamber control from voteview</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render report.qmd                  <span class="co"># rebuild this page</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Everything above regenerates from public data. Full method: <a href="PRE_REGISTRATION.md"><code>PRE_REGISTRATION.md</code></a>.</p>
<hr>
<p><strong>Cite this:</strong> Frisbie, F. (2026). <em>Do Presidents Govern by Decree When They Lose Congress?</em> (v1.0.0). Zenodo. <a href="https://doi.org/10.5281/zenodo.21270973" class="uri">https://doi.org/10.5281/zenodo.21270973</a></p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Do Presidents Govern by Decree When They Lose Congress?"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "A pre-registered test of executive orders under divided government, 1953–2025"</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Frank Frisbie"</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">    output-file: index.html</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: cosmo</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-location: left</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: kable</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-width: 9</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-height: 4.5</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup}</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr); <span class="fu">library</span>(readr); <span class="fu">library</span>(broom); <span class="fu">library</span>(ggplot2)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/00_shared.R"</span>)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>eos     <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/executive_orders_raw.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>divided <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/divided_government.csv"</span>,   <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>panel   <span class="ot">&lt;-</span> <span class="fu">build_panel</span>(eos, divided)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>models  <span class="ot">&lt;-</span> <span class="fu">fit_models</span>(panel)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>nb      <span class="ot">&lt;-</span> models[[<span class="st">"Negative binomial (primary)"</span>]]</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Profile-likelihood CIs where computable; Wald-CI fallback only when profiling</span></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a><span class="co"># fails. The president fixed-effects spec has complete separation on this small</span></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="co"># sample, so its profile CI cannot be computed - this keeps that spec in the</span></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="co"># robustness table (as pre-registered) instead of aborting the render. The other</span></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a><span class="co"># three specs are unaffected and keep their exact profile intervals.</span></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>tidy_ci <span class="ot">&lt;-</span> <span class="cf">function</span>(m) {</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tryCatch</span>(</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>(m, <span class="at">conf.int =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>      z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>      <span class="fu">tidy</span>(m) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">conf.low  =</span> estimate <span class="sc">-</span> z <span class="sc">*</span> std.error,</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>                        <span class="at">conf.high =</span> estimate <span class="sc">+</span> z <span class="sc">*</span> std.error)</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## The claim being tested</span></span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>A familiar story about American politics: when a president faces a Congress controlled by the other party, they stop legislating and start *decreeing*, reaching for the executive order to act without lawmakers. It's intuitive, it's repeated constantly, and it has serious scholarship behind it (Howell, *Power Without Persuasion*; Mayer, *With the Stroke of a Pen*).</span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>This is a small, deliberately narrow test of one measurable piece of that story: **does the raw volume of executive orders rise under divided government?**</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a><span class="fu">## This analysis was pre-registered</span></span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>The hypothesis and the full model specification were frozen **before any data was pulled or seen**. See <span class="co">[</span><span class="ot">`PRE_REGISTRATION.md`</span><span class="co">](PRE_REGISTRATION.md)</span>. That means the result below was not reverse-engineered to be interesting. A clean null is reported as honestly as a clean positive.</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a><span class="fu">## What counts as "divided," and where the numbers come from</span></span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>Every number here traces to a public source:</span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Executive orders**: the complete 1953–2025 record, counted by signing date. The Federal Register's search API only has full coverage from 1994 on, so the pipeline combines its pre-1994 disposition tables with the 1994+ API, then validates per-president totals against published counts and refuses to run if the data is incomplete.</span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Party control of each chamber**: hand-verified per Congress (to correctly handle caucusing independents and VP-tiebreak Senates that a naive party count miscodes), and independently cross-checked against <span class="co">[</span><span class="ot">voteview.com</span><span class="co">](https://voteview.com)</span> DW-NOMINATE records.</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Presidential party**: a 14-row administrations table.</span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a>A year is coded **divided** when the president's party does not control *both* chambers.</span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a><span class="in">```{r overview}</span></span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a>panel <span class="sc">|&gt;</span></span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(control) <span class="sc">|&gt;</span></span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at"># years</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">n</span>(), <span class="st">`</span><span class="at">avg EOs/yr</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(eo_count), <span class="dv">1</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a><span class="in">```{r timeline}</span></span>
<span id="cb10-77"><a href="#cb10-77" aria-hidden="true" tabindex="-1"></a><span class="fu">make_timeline_plot</span>(panel)</span>
<span id="cb10-78"><a href="#cb10-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-79"><a href="#cb10-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-80"><a href="#cb10-80" aria-hidden="true" tabindex="-1"></a><span class="fu">## The result</span></span>
<span id="cb10-81"><a href="#cb10-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-82"><a href="#cb10-82" aria-hidden="true" tabindex="-1"></a><span class="in">```{r result}</span></span>
<span id="cb10-83"><a href="#cb10-83" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">tidy</span>(nb, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"divided_government"</span>)</span>
<span id="cb10-84"><a href="#cb10-84" aria-hidden="true" tabindex="-1"></a>irr <span class="ot">&lt;-</span> <span class="fu">exp</span>(res<span class="sc">$</span>estimate); lo <span class="ot">&lt;-</span> <span class="fu">exp</span>(res<span class="sc">$</span>conf.low); hi <span class="ot">&lt;-</span> <span class="fu">exp</span>(res<span class="sc">$</span>conf.high)</span>
<span id="cb10-85"><a href="#cb10-85" aria-hidden="true" tabindex="-1"></a>sig <span class="ot">&lt;-</span> (res<span class="sc">$</span>conf.low <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|</span> (res<span class="sc">$</span>conf.high <span class="sc">&lt;</span> <span class="dv">0</span>)   <span class="co"># CI excludes zero?</span></span>
<span id="cb10-86"><a href="#cb10-86" aria-hidden="true" tabindex="-1"></a>dir <span class="ot">&lt;-</span> <span class="cf">if</span> (res<span class="sc">$</span>estimate <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="st">"more"</span> <span class="cf">else</span> <span class="st">"fewer"</span></span>
<span id="cb10-87"><a href="#cb10-87" aria-hidden="true" tabindex="-1"></a>verdict <span class="ot">&lt;-</span> <span class="cf">if</span> (sig <span class="sc">&amp;&amp;</span> res<span class="sc">$</span>estimate <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb10-88"><a href="#cb10-88" aria-hidden="true" tabindex="-1"></a>  <span class="st">"supports H1: divided government is associated with measurably more executive orders."</span></span>
<span id="cb10-89"><a href="#cb10-89" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span> (sig <span class="sc">&amp;&amp;</span> res<span class="sc">$</span>estimate <span class="sc">&lt;</span> <span class="dv">0</span>) {</span>
<span id="cb10-90"><a href="#cb10-90" aria-hidden="true" tabindex="-1"></a>  <span class="st">"runs *against* H1: divided government is associated with measurably fewer executive orders."</span></span>
<span id="cb10-91"><a href="#cb10-91" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb10-92"><a href="#cb10-92" aria-hidden="true" tabindex="-1"></a>  <span class="st">"does **not** support H1: the divided-government association is not statistically distinguishable from zero in this sample."</span></span>
<span id="cb10-93"><a href="#cb10-93" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-94"><a href="#cb10-94" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-95"><a href="#cb10-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-96"><a href="#cb10-96" aria-hidden="true" tabindex="-1"></a>**The cleanest specification shows no reliable effect.** Comparing each president against himself with president fixed effects, moving between unified and divided control is associated with essentially no change in how many executive orders a president issues (within-president estimate −0.07, 95% CI includes zero). The popular claim that presidents govern by decree when they lose Congress is not supported here. That null is not bulletproof, though: it turns on how a handful of transition years are coded, which the section <span class="co">[</span><span class="ot">How fragile is this null?</span><span class="co">](#how-fragile-is-this-null)</span> works through in full.</span>
<span id="cb10-97"><a href="#cb10-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-98"><a href="#cb10-98" aria-hidden="true" tabindex="-1"></a>The pooled estimate points the other way, and does not survive that check. In the pre-registered primary model (pooled negative binomial), a divided-government year carries about **`r round(irr, 2)`×** the executive-order rate of a unified-government year (95% CI <span class="in">`r round(lo,2)`</span>–<span class="in">`r round(hi,2)`</span>), that is, <span class="in">`r dir`</span> orders. Taken by itself, the data <span class="in">`r verdict`</span> But it is the pooled estimate only: it does not survive president fixed effects, so it is best read as a between-president composition pattern (some presidents simply governed in high-EO eras under unified control), not as evidence that divided government itself changes how often a president reaches for the pen. The conclusion the analysis lands on is "no reliable effect," not "fewer."</span>
<span id="cb10-99"><a href="#cb10-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-100"><a href="#cb10-100" aria-hidden="true" tabindex="-1"></a>Full coefficient table for the primary specification:</span>
<span id="cb10-101"><a href="#cb10-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-102"><a href="#cb10-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r primary-table}</span></span>
<span id="cb10-103"><a href="#cb10-103" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(nb, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-104"><a href="#cb10-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), \(x) <span class="fu">round</span>(x, <span class="dv">3</span>)))</span>
<span id="cb10-105"><a href="#cb10-105" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-106"><a href="#cb10-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-107"><a href="#cb10-107" aria-hidden="true" tabindex="-1"></a><span class="fu">### Robustness</span></span>
<span id="cb10-108"><a href="#cb10-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-109"><a href="#cb10-109" aria-hidden="true" tabindex="-1"></a>The pre-registration committed to reporting four specifications, not just the favorable one. The estimated divided-government effect across all of them:</span>
<span id="cb10-110"><a href="#cb10-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-111"><a href="#cb10-111" aria-hidden="true" tabindex="-1"></a><span class="in">```{r robustness}</span></span>
<span id="cb10-112"><a href="#cb10-112" aria-hidden="true" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">map_dfr</span>(<span class="fu">names</span>(models), \(nm) {</span>
<span id="cb10-113"><a href="#cb10-113" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy_ci</span>(models[[nm]]) <span class="sc">|&gt;</span></span>
<span id="cb10-114"><a href="#cb10-114" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"divided_government"</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-115"><a href="#cb10-115" aria-hidden="true" tabindex="-1"></a>    <span class="fu">transmute</span>(<span class="at">specification =</span> nm, <span class="at">estimate =</span> <span class="fu">round</span>(estimate, <span class="dv">3</span>),</span>
<span id="cb10-116"><a href="#cb10-116" aria-hidden="true" tabindex="-1"></a>              <span class="at">conf.low =</span> <span class="fu">round</span>(conf.low, <span class="dv">3</span>), <span class="at">conf.high =</span> <span class="fu">round</span>(conf.high, <span class="dv">3</span>),</span>
<span id="cb10-117"><a href="#cb10-117" aria-hidden="true" tabindex="-1"></a>              <span class="at">p.value =</span> <span class="fu">round</span>(p.value, <span class="dv">3</span>))</span>
<span id="cb10-118"><a href="#cb10-118" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-119"><a href="#cb10-119" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-120"><a href="#cb10-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-121"><a href="#cb10-121" aria-hidden="true" tabindex="-1"></a>**Reading across specifications.** In the pooled models (negative binomial, Poisson, OLS), divided-government years carry a lower executive-order rate than unified years, about 0.80× in the primary model, statistically distinguishable from zero. That already cuts against H1, which predicted *more* unilateral action under divided government. But the effect does not survive president fixed effects: within a given presidency, moving between unified and divided control is associated with essentially no change (−0.07, 95% CI includes zero). As the pre-registration flagged in advance, an effect that appears pooled but vanishes within-president is best read as a between-president composition pattern (some presidents simply governed in high-EO eras under unified control), not as evidence that divided government itself changes how often a president reaches for the pen. The raw averages agree: opposition-Congress years (48.2/yr) edge out split-Congress years (43.6/yr), so there is no clean "more division, fewer orders" gradient.</span>
<span id="cb10-122"><a href="#cb10-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-123"><a href="#cb10-123" aria-hidden="true" tabindex="-1"></a>**Bottom line.** The popular claim that presidents govern by decree when they lose Congress is not supported here: the pooled association runs the other way (fewer, not more), and it does not survive president fixed effects. But this null is not robust to coding choices. An independent coding disagrees with ours on three of seventy-three years, and adopting it in full would flip the fixed-effects estimate to a significant negative effect. The honest read, developed in the next section, is that **neither the effect nor its absence is robust to how a handful of transition years are coded.**</span>
<span id="cb10-124"><a href="#cb10-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-125"><a href="#cb10-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## How fragile is this null?</span></span>
<span id="cb10-126"><a href="#cb10-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-127"><a href="#cb10-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r sensitivity}</span></span>
<span id="cb10-128"><a href="#cb10-128" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(MASS))</span>
<span id="cb10-129"><a href="#cb10-129" aria-hidden="true" tabindex="-1"></a>cap <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/cap_divided_government.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-130"><a href="#cb10-130" aria-hidden="true" tabindex="-1"></a>fe_irrp <span class="ot">&lt;-</span> <span class="cf">function</span>(p){ m <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="fu">update</span>(EO_FORMULA, . <span class="sc">~</span> . <span class="sc">+</span> <span class="fu">factor</span>(president)), <span class="at">data =</span> p)</span>
<span id="cb10-131"><a href="#cb10-131" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m))[<span class="st">"divided_government"</span>, ]; <span class="fu">c</span>(<span class="at">irr =</span> <span class="fu">exp</span>(<span class="fu">unname</span>(s[<span class="dv">1</span>])), <span class="at">p =</span> <span class="fu">unname</span>(s[<span class="dv">4</span>])) }</span>
<span id="cb10-132"><a href="#cb10-132" aria-hidden="true" tabindex="-1"></a>setyr <span class="ot">&lt;-</span> <span class="cf">function</span>(p, yrs, v){ p<span class="sc">$</span>divided_government[p<span class="sc">$</span>year <span class="sc">%in%</span> yrs] <span class="ot">&lt;-</span> v; p }</span>
<span id="cb10-133"><a href="#cb10-133" aria-hidden="true" tabindex="-1"></a>panel_cap <span class="ot">&lt;-</span> panel; panel_cap<span class="sc">$</span>divided_government <span class="ot">&lt;-</span> cap<span class="sc">$</span>cap_divided[<span class="fu">match</span>(panel<span class="sc">$</span>year, cap<span class="sc">$</span>year)]</span>
<span id="cb10-134"><a href="#cb10-134" aria-hidden="true" tabindex="-1"></a>fe_ours <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(panel)</span>
<span id="cb10-135"><a href="#cb10-135" aria-hidden="true" tabindex="-1"></a>fe_j    <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(<span class="fu">setyr</span>(panel, <span class="fu">c</span>(<span class="dv">2001</span>,<span class="dv">2002</span>), <span class="dv">0</span>))   <span class="co"># CAP's Jeffords convention only</span></span>
<span id="cb10-136"><a href="#cb10-136" aria-hidden="true" tabindex="-1"></a>fe_2018 <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(<span class="fu">setyr</span>(panel, <span class="dv">2018</span>, <span class="dv">1</span>))           <span class="co"># CAP's 2018 only</span></span>
<span id="cb10-137"><a href="#cb10-137" aria-hidden="true" tabindex="-1"></a>fe_cap  <span class="ot">&lt;-</span> <span class="fu">fe_irrp</span>(panel_cap)                        <span class="co"># full CAP coding</span></span>
<span id="cb10-138"><a href="#cb10-138" aria-hidden="true" tabindex="-1"></a>irrp <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sprintf</span>(<span class="st">"IRR %.3f, p = %.3f"</span>, x[<span class="st">"irr"</span>], x[<span class="st">"p"</span>])</span>
<span id="cb10-139"><a href="#cb10-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-140"><a href="#cb10-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-141"><a href="#cb10-141" aria-hidden="true" tabindex="-1"></a>To see how sturdy the "no reliable effect" conclusion is, I checked it against an **independent coding** of the same orders: the Comparative Agendas Project executive-orders dataset (1945-2025), which codes each order with its own divided-government flag. Collapsed to the year level, **it agrees with our coding on 70 of 73 years.** But the three disagreements are enough to move the headline.</span>
<span id="cb10-142"><a href="#cb10-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-143"><a href="#cb10-143" aria-hidden="true" tabindex="-1"></a>Under our coding, the president-fixed-effects estimate shows **no reliable effect** (`r irrp(fe_ours)`). Under CAP's full coding, the same model would show a **statistically significant negative effect** (<span class="in">`r irrp(fe_cap)`</span>), which would overturn the headline from "no reliable effect" to "reliably fewer orders under divided government."</span>
<span id="cb10-144"><a href="#cb10-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-145"><a href="#cb10-145" aria-hidden="true" tabindex="-1"></a>Because the disagreement is only three years, it is worth seeing exactly how each one moves the fixed-effects estimate:</span>
<span id="cb10-146"><a href="#cb10-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-147"><a href="#cb10-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r sensitivity-table}</span></span>
<span id="cb10-148"><a href="#cb10-148" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb10-149"><a href="#cb10-149" aria-hidden="true" tabindex="-1"></a>  <span class="at">Coding =</span> <span class="fu">c</span>(<span class="st">"Ours (hand-coded control)"</span>,</span>
<span id="cb10-150"><a href="#cb10-150" aria-hidden="true" tabindex="-1"></a>             <span class="st">"+ CAP's 2001-2002 (Jeffords) only"</span>,</span>
<span id="cb10-151"><a href="#cb10-151" aria-hidden="true" tabindex="-1"></a>             <span class="st">"+ CAP's 2018 only"</span>,</span>
<span id="cb10-152"><a href="#cb10-152" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Full CAP coding (all three years)"</span>),</span>
<span id="cb10-153"><a href="#cb10-153" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">IRR (divided govt)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">c</span>(fe_ours[<span class="st">"irr"</span>], fe_j[<span class="st">"irr"</span>], fe_2018[<span class="st">"irr"</span>], fe_cap[<span class="st">"irr"</span>]), <span class="dv">3</span>),</span>
<span id="cb10-154"><a href="#cb10-154" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">p-value</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">c</span>(fe_ours[<span class="st">"p"</span>], fe_j[<span class="st">"p"</span>], fe_2018[<span class="st">"p"</span>], fe_cap[<span class="st">"p"</span>]), <span class="dv">3</span>),</span>
<span id="cb10-155"><a href="#cb10-155" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Reliable effect?</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"no"</span>, <span class="st">"no"</span>, <span class="st">"yes (negative)"</span>))</span>
<span id="cb10-156"><a href="#cb10-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-157"><a href="#cb10-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-158"><a href="#cb10-158" aria-hidden="true" tabindex="-1"></a>Adopting CAP's 2001-2002 coding alone leaves the null intact (p = <span class="in">`r sprintf("%.3f", fe_j["p"])`</span>). Adopting CAP's 2018 coding alone leaves it intact (p = <span class="in">`r sprintf("%.3f", fe_2018["p"])`</span>). Only both together cross into significance (p = <span class="in">`r sprintf("%.3f", fe_cap["p"])`</span>).</span>
<span id="cb10-159"><a href="#cb10-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-160"><a href="#cb10-160" aria-hidden="true" tabindex="-1"></a>Our reasoning, without hedging:</span>
<span id="cb10-161"><a href="#cb10-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-162"><a href="#cb10-162" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**2001-2002 is a genuine convention difference.** CAP codes by which party *organized* the chamber; we hand-code *actual* control. After Senator Jeffords left the Republican caucus in mid-2001, the Senate was Democratic-controlled, so we code 2001-2002 as divided. This choice was frozen in advance (pre-registration, limitation 3), not chosen to produce a result.</span>
<span id="cb10-163"><a href="#cb10-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**2018 is not a convention difference. It is an apparent error.** 2018 falls in the 115th Congress, which was unified Republican control. CAP files 2018's orders under the 116th Congress, which did not convene until January 2019. We do not adopt a coding we believe is mistaken in order to obtain significance.</span>
<span id="cb10-164"><a href="#cb10-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-165"><a href="#cb10-165" aria-hidden="true" tabindex="-1"></a>So the null **survives every individually defensible recoding, and breaks only under a combination that includes the apparent error.** That is the most defensible reading of the evidence. But the plain fact that a three-year recoding in a seventy-three-year series can flip the result means the honest conclusion is the one stated above: **neither the effect nor its absence is robust to coding choices.** A longer series, or a settled convention for mid-Congress control flips, would be needed to say more.</span>
<span id="cb10-166"><a href="#cb10-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-167"><a href="#cb10-167" aria-hidden="true" tabindex="-1"></a><span class="fu">## What this does and doesn't show</span></span>
<span id="cb10-168"><a href="#cb10-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-169"><a href="#cb10-169" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Counts ≠ significance.** This measures the *volume* of unilateral action, not its weight. A single consequential order and a routine administrative one count the same. Raw counts are known to undercount the orders that matter most.</span>
<span id="cb10-170"><a href="#cb10-170" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**EOs are one channel.** Memoranda and proclamations are other unilateral tools, out of scope here.</span>
<span id="cb10-171"><a href="#cb10-171" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Small sample.** ~73 years means wide confidence intervals; that uncertainty is shown, not smoothed over.</span>
<span id="cb10-172"><a href="#cb10-172" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Mid-Congress control flips** (e.g., the 2001 Senate) are coded at the Congress level and tested in robustness.</span>
<span id="cb10-173"><a href="#cb10-173" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Completeness was the hard part.** An initial pull silently captured only ~1,485 of the ~3,800 orders because of the API's pre-1994 gap, which by itself faked a result. The analysis proceeds only after a per-president completeness check passes.</span>
<span id="cb10-174"><a href="#cb10-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-175"><a href="#cb10-175" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reproduce this</span></span>
<span id="cb10-176"><a href="#cb10-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-177"><a href="#cb10-177" aria-hidden="true" tabindex="-1"></a><span class="in">```bash</span></span>
<span id="cb10-178"><a href="#cb10-178" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> R/01_pull_executive_orders.R     <span class="co"># pull EOs from the Federal Register</span></span>
<span id="cb10-179"><a href="#cb10-179" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> R/02_build_divided_government.R   <span class="co"># derive chamber control from voteview</span></span>
<span id="cb10-180"><a href="#cb10-180" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render report.qmd                  <span class="co"># rebuild this page</span></span>
<span id="cb10-181"><a href="#cb10-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-182"><a href="#cb10-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-183"><a href="#cb10-183" aria-hidden="true" tabindex="-1"></a>Everything above regenerates from public data. Full method: <span class="co">[</span><span class="ot">`PRE_REGISTRATION.md`</span><span class="co">](PRE_REGISTRATION.md)</span>.</span>
<span id="cb10-184"><a href="#cb10-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-185"><a href="#cb10-185" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb10-186"><a href="#cb10-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-187"><a href="#cb10-187" aria-hidden="true" tabindex="-1"></a>**Cite this:** Frisbie, F. (2026). *Do Presidents Govern by Decree When They Lose Congress?* (v1.0.0). Zenodo. <span class="ot">&lt;https://doi.org/10.5281/zenodo.21270973&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>